using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Enigma.Icons.Generator;

/// <summary>
/// The single write-or-compare path every artifact goes through.
/// </summary>
/// <remarks>
/// Each artifact is rendered to a <c>byte[]</c> first and then either written or byte-compared
/// against the file on disk. One renderer, two consumers — that is what makes <c>--check</c>
/// (SPEC §8.5) a real proof rather than a parallel reimplementation free to drift. In check mode
/// nothing is created, not even the <c>Assets</c> directory.
/// </remarks>
internal sealed class OutputTarget
{
    /// <summary>
    /// The preamble of both generated C# files. It carries no date, no version and no host path:
    /// anything that changed between runs would break byte-determinism, and the snapshot version
    /// already lives in <c>docs/reference/phosphor/README.md</c>.
    /// </summary>
    internal const string GeneratedFileHeader = """
        // <auto-generated/>
        // Produced by tools/Enigma.Icons.Generator - do not edit by hand; run the generator instead.
        // Icon artwork from Phosphor Icons, MIT licensed, Copyright (c) 2020 Phosphor Icons.
        // See THIRD-PARTY-NOTICES.md at the repository root.
        #nullable enable

        """;

    // UTF-8 without a byte-order mark, per SPEC §7.2 and §8.4.
    private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

    private readonly string _outputDirectory;
    private readonly bool _checkOnly;
    private readonly List<string> _differences = [];

    private int _emitted;

    /// <summary>Creates a target rooted at <paramref name="outputDirectory"/>.</summary>
    /// <param name="outputDirectory">The <c>Enigma.Icons.Phosphor</c> project directory.</param>
    /// <param name="checkOnly">When true, compare instead of write and create nothing.</param>
    internal OutputTarget(string outputDirectory, bool checkOnly)
    {
        _outputDirectory = outputDirectory;
        _checkOnly = checkOnly;
    }

    /// <summary>The artifacts that differ from the committed bytes, described relative to the output directory.</summary>
    internal IReadOnlyList<string> Differences => _differences;

    /// <summary>How many artifacts were written or compared.</summary>
    internal int Emitted => _emitted;

    /// <summary>
    /// Encodes generated text as the bytes that go to disk: LF line endings only — never
    /// <c>Environment.NewLine</c>, and never whatever ending this tool's own sources happen to
    /// carry — UTF-8, no BOM.
    /// </summary>
    internal static byte[] ToUtf8(string text) => Utf8NoBom.GetBytes(text.Replace("\r\n", "\n"));

    /// <summary>Writes or compares one artifact.</summary>
    /// <param name="relativePath">The artifact's path relative to the output directory, using '/'.</param>
    /// <param name="content">The rendered bytes.</param>
    internal void Emit(string relativePath, byte[] content)
    {
        string fullPath = Path.Combine(
            _outputDirectory,
            relativePath.Replace('/', Path.DirectorySeparatorChar));

        _emitted++;

        if (_checkOnly)
        {
            Compare(relativePath, fullPath, content);
            return;
        }

        string? directory = Path.GetDirectoryName(fullPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllBytes(fullPath, content);
    }

    private void Compare(string relativePath, string fullPath, byte[] expected)
    {
        if (!File.Exists(fullPath))
        {
            _differences.Add(relativePath + ": missing.");
            return;
        }

        byte[] actual = File.ReadAllBytes(fullPath);

        int shared = Math.Min(actual.Length, expected.Length);
        int offset = -1;
        for (int i = 0; i < shared; i++)
        {
            if (actual[i] != expected[i])
            {
                offset = i;
                break;
            }
        }

        if (offset < 0 && actual.Length == expected.Length)
        {
            return;
        }

        var message = new StringBuilder();
        message.Append(CultureInfo.InvariantCulture, $"{relativePath}: {actual.Length} bytes on disk, {expected.Length} bytes generated");

        if (offset >= 0)
        {
            message.Append(CultureInfo.InvariantCulture, $"; first difference at offset {offset}");
        }
        else
        {
            message.Append(CultureInfo.InvariantCulture, $"; identical up to offset {shared}, then truncated or extended");
        }

        message.Append('.');
        _differences.Add(message.ToString());
    }
}
